title: "Talha Shahbaz"
description: "Senior Software Engineer – .NET Core | Microservices | FinTech"
theme: jekyll-theme-slate
show_downloads: false

# Optional footer
footer: "© 2025 Talha Shahbaz"