title: "Talha Shahbaz"
description: "Senior Backend Engineer – SiFi | .NET | Microservices | FinTech"
theme: jekyll-theme-slate
show_downloads: false

# Optional footer

footer: "© 2025 Talha Shahbaz"
